version: '3'
services:
  db:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile

    environment:
      MYSQL_ROOT_PASSWORD: 13656195
      MYSQL_DATABASE: url_shortener_db
      MYSQL_USER: root
      MYSQL_PASSWORD: 13656195
    container_name: urlshortener_db
    ports:
      - "3306:3306"
    tty: true
  app:
    build:
      context: .
      dockerfile: ./docker/golang/Dockerfile
    container_name: urlshortener_go
    ports:
      - "8080:8080"
    tty: true
    depends_on:
      - db